export const CHANGE_CURRENT_PATH = 'CHANGE_CURRENT_PATH';
export const CHANGE_NAV_KEY = 'CHANGE_NAV_KEY';

export const FETCH_NEW_MOVIE = 'FETCH_NEW_MOVIE';
export const CHANGE_KEYWORDS = 'CHANGE_KEYWORDS';