export default [
    {
        path: '/',
        msg: 'Dashboard',
        navKey: 0
    }, {
        path: '/line/1',
        msg: 'line-1',
        navKey: 1
    }, {
        path: '/line/2',
        msg: 'line-2',
        navKey: 1
    }, {
        path: '/line/3',
        msg: 'line-3',
        navKey: 1
    }, {
        path: '/bar/1',
        msg: 'bar-1',
        navKey: 2
    }, {
        path: '/bar/2',
        msg: 'bar-2',
        navKey: 2
    }, {
        path: '/bar/3',
        msg: 'bar-3',
        navKey: 2
    }, {
        path: '/pie/1',
        msg: 'pie-1',
        navKey: 3
    }, {
        path: '/pie/2',
        msg: 'pie-2',
        navKey: 3
    }, {
        path: '/pie/3',
        msg: 'pie-3',
        navKey: 3
    }, {
        path: '/douban/movies',
        msg: '电影',
        navKey: 4
    }, {
        path: '/douban/musics',
        msg: '音乐',
        navKey: 4
    }, {
        path: '/douban/books',
        msg: '小说',
        navKey: 4
    }
]